<p>捕获 <code>System.Exception</code> 似乎是个能处理多个可能异常的有效方法。然而不幸的是，它会捕获所有的异常类型，甚至包括那些你并不打算捕获的。为避免误解应使用异常过滤，或者把每种异常的类型写在不同的 <code>catch</code> 语句块中。</p>
<h2>不合规的代码示例</h2>
<pre>
try
{
  // 此处是一些可能抛出FileNotFoundException或IOException的操作
}
catch (Exception e) // 不合规
{
  // 记录异常……
}
</pre>
<h2>合规的解决方案</h2>
<pre>
try
{
  // 此处进行某些操作
}
catch (Exception e) when (e is FileNotFoundException || e is IOException)
{
  // 此处进行某些操作
}

</pre>
<h2>例外</h2>
<p>还可以在 <code>catch</code> 语句块的最后一条语句里捕获 <code>System.Exception</code> 并 <code>throw</code> 它。但这是最差的选项，因为这是一种老式的代码，比起异常过滤它有额外的性能损耗。</p>
<pre>
try
{
  // 此处进行某些操作
}
catch (Exception e)
{
  if (e is FileNotFoundException || e is IOException)
  {
    // 此处进行某些操作
  }
  else
  {
    throw;
  }
}
</pre>
<h2>请参阅</h2>
<ul>
	<li> <a href="http://cwe.mitre.org/data/definitions/396.html">MITRE, CWE-396</a> - Declaration of Catch for Generic Exception </li>
</ul>

